Feature/#13 localstorage
dennisxu54/second-learning-react pull request #14
Opened 2021-11-11 23:00 UTC by dennisxu54

closes #13

2021-11-11 23:02 UTC, Chidoge requested changes

2021-11-11 23:02 UTC, Chidoge commented on src/pages/home-page/index.tsx
> +    localStorage.setItem(id.toString(), JSON.stringify(item))
You should not be writing each task to a separate key, instead a better approach would be to set the entire list under a storage key named `list` and stringifying the array and passing that in.

2021-11-11 23:02 UTC, Chidoge commented on src/components/task-card/TaskCard.tsx
> +    localStorage.removeItem(id.toString())
Read comment about what should be passed in

2021-11-15 00:47 UTC, Chidoge commented on src/pages/task-page/index.tsx
> +  localStorage.setItem("List", JSON.stringify(list))
Nop, you only want to set the list whenever you add an item to the list, not here

2021-11-15 00:47 UTC, Chidoge requested changes

2021-11-15 00:47 UTC, Chidoge commented on src/pages/home-page/index.tsx
> +  useEffect(() => {
Same deal here

2021-11-15 23:59 UTC, Chidoge requested changes

2021-11-15 23:59 UTC, Chidoge commented on src/pages/home-page/index.tsx
> +    const dataItem = localStorage.getItem('list')
Almost there, I want you to be to updating `localStorage` within the `addItemToList` function

2021-11-15 23:59 UTC, Chidoge commented on src/components/task-card/TaskCard.tsx
> +    const dataItem = localStorage.getItem('list')
Ditto here

2021-11-17 23:29 UTC, dennisxu54 commented
![image](https://user-images.githubusercontent.com/43261535/142298620-6d93e033-52f4-43fa-abb3-92fcc3d51fc8.png)

![image](https://user-images.githubusercontent.com/43261535/142298647-ddd1ec88-e712-4c08-b060-2750a48ab845.png)

Add three entries
![image](https://user-images.githubusercontent.com/43261535/142298686-4e0286ee-7cc3-4ed1-8302-c2fbe241b400.png)

![image](https://user-images.githubusercontent.com/43261535/142298703-3461f7d7-be8e-42e8-8073-a3149a39c05d.png)

![image](https://user-images.githubusercontent.com/43261535/142298713-f30ef8ee-c39c-42d7-8024-836eb4d28268.png)

![image](https://user-images.githubusercontent.com/43261535/142298739-357cacb0-7edc-435d-892b-57ca5e8d4caf.png)

![image](https://user-images.githubusercontent.com/43261535/142298771-28cb0980-560e-44d3-a792-6fd34d836e70.png)

page refresh
![image](https://user-images.githubusercontent.com/43261535/142298796-2ad875d7-e30f-4121-8388-b6e4f5e521bb.png)

![image](https://user-images.githubusercontent.com/43261535/142298809-29cae8dd-b9b1-4af2-8f81-b419c076996a.png)

2021-11-17 23:31 UTC, Chidoge commented on src/store/store.ts
> +  let preLoadedState
Have you checked that this doesn't cause a crash/error when your `localStorage` is empty?

2021-11-17 23:34 UTC, dennisxu54 commented
![image](https://user-images.githubusercontent.com/43261535/142299247-60463609-ae5e-4407-be5e-ef5618af3f71.png)

![image](https://user-images.githubusercontent.com/43261535/142299261-2f082ad1-b93c-4e69-a3b2-aa71fc573f58.png)

2021-11-17 23:46 UTC, Chidoge commented
LGTM

2021-11-17 23:46 UTC, Chidoge approved these changes

2021-11-17 23:46 UTC, merged